PARTNER_ROLE = 1
ORGANISATION_ROLE = 2
SUPERUSER_ROLE = 3
ROLES = (
    (PARTNER_ROLE, 'Partner'),
    (ORGANISATION_ROLE, 'Organization'),
    (SUPERUSER_ROLE, 'Superuser')
)

PUBLIC_ROLES = (PARTNER_ROLE, ORGANISATION_ROLE)
