# Generated by Django 2.2.7 on 2019-11-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sending date'),
        ),
        migrations.AlterModelOptions(
            name='loanrequest',
            options={'ordering': ('-created',), 'verbose_name': 'loan request', 'verbose_name_plural': 'loan request'},
        ),
    ]
